services:
  lab_06_web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: lab_06_web
    image: lab_06_web:0.1
    command: bash -c "bundle exec rake db:create && bundle exec rake db:migrate && ./bin/rails server -b 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    networks:
      - lab_06_network
    volumes:
      - ./:/rails

networks:
  lab_06_network:
    external: true